// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Frame(props) {
  var frame = props.frame;
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("span", {
                      children: frame.file_name,
                      className: "text-zinc-500 text-xs"
                    }),
                JsxRuntime.jsx("span", {
                      children: frame.func_name,
                      className: "text-md"
                    }),
                JsxRuntime.jsx("span", {
                      children: String(frame.line_no)
                    })
              ],
              className: "w-full flex items-center space-x-4 text-sm text-zinc-300 " + (
                props.isSelected ? "bg-red-500" : ""
              )
            });
}

var make = Frame;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
