// Generated by ReScript, PLEASE EDIT WITH CARE


function keepOks(arr) {
  return arr.filter(function (el) {
                if (el.TAG === "Ok") {
                  return true;
                } else {
                  return false;
                }
              }).map(function (el) {
              if (el.TAG === "Ok") {
                return el._0;
              }
              throw {
                    RE_EXN_ID: "Assert_failure",
                    _1: [
                      "Utils.res",
                      14,
                      20
                    ],
                    Error: new Error()
                  };
            });
}

var Utils = {
  keepOks: keepOks
};

export {
  Utils ,
}
/* No side effect */
